export interface Auth {
  id?: number;
  username?: string;
  fullname?: string;
  email: string;
  role?: string;
  password: string;
  access_token?: string;
  refresh_token?: string;
}

/**
 * Represents the decoded JWT payload as generated by AuthService.generateJwt().
 *
 * Fields actually embedded in the token:
 *   { jti, sub, role, token_type }
 *
 * Standard JWT fields added automatically by jsonwebtoken:
 *   iat, exp
 */
export interface TokenPayload {
  /** User ID (maps to UserModel.id) */
  sub: number;
  /** Unique token ID (uuidv7) — used to look up / revoke sessions */
  jti: string;
  /** User role (maps to UserRole enum) */
  role: string;
  /** Discriminates access vs. refresh tokens */
  token_type: 'access_token' | 'refresh_token';
  /** Issued-at timestamp (seconds, set by JWT library) */
  iat?: number;
  /** Expiry timestamp (seconds, set by JWT library) */
  exp?: number;
}
